import {createClient} from '@supabase/supabase-js';
const c=createClient('https://ehifskiigrfpxeiruyxr.supabase.co','sb_publishable_ne8xIO5aoko5eW4ONLfBRQ_uyfBBhYy',{auth:{storageKey:'sponti-provider-auth',persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}),root=document.querySelector('[data-provider-account]'),status=root.querySelector('[data-provider-status]');let user=null,profile=null,busy=false,recovery=['invite','recovery'].includes(new URLSearchParams(location.hash.slice(1)).get('type'));
const msg=(t,e=false)=>{status.textContent=t;status.hidden=!t;status.classList.toggle('is-error',e)};function draw(){root.querySelector('[data-provider-loading]').hidden=true;root.querySelector('[data-provider-guest]').hidden=!!user;root.querySelector('[data-provider-member]').hidden=!user;root.querySelector('[data-provider-password]').hidden=!user;root.querySelector('[data-password-title]').textContent=recovery?'Passwort festlegen.':'Passwort ändern.';if(user){root.querySelector('[data-provider-email]').textContent=user.email||'';root.querySelector('[data-provider-company]').textContent=profile?.company||'Dein Anbieterprofil.';const f=root.querySelector('[data-provider-form="profile"]');['company','contact_name','phone','location','website','category','description'].forEach(k=>{if(f.elements[k])f.elements[k].value=profile?.[k]||''})}}async function load(){const r=await c.auth.getUser();user=r.data.user;profile=null;if(user){const p=await c.from('provider_profiles').select('*').eq('user_id',user.id).maybeSingle();if(p.error)throw p.error;profile=p.data;if(!profile)throw new Error('Für dieses Konto ist noch kein Anbieterprofil freigeschaltet. Bitte kontaktiere Sponti.')}draw();if(user){await loadCourses();renderPreview()}}function mode(m){root.querySelectorAll('[data-provider-panel]').forEach(x=>x.hidden=x.dataset.providerPanel!==m);root.querySelectorAll('[data-provider-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.providerMode===m)))}root.querySelectorAll('[data-provider-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.providerMode));if(new URLSearchParams(location.search).get('mode')==='register')mode('register');root.querySelectorAll('[data-provider-form]').forEach(f=>f.onsubmit=async e=>{e.preventDefault();msg('');const d=new FormData(f),type=f.dataset.providerForm;try{if(type==='login'){const r=await c.auth.signInWithPassword({email:String(d.get('email')).trim(),password:String(d.get('password'))});if(r.error)throw r.error;await load()}if(type==='profile'){const values={user_id:user.id,company:String(d.get('company')).trim(),contact_name:String(d.get('contact_name')).trim(),phone:String(d.get('phone')).trim(),location:String(d.get('location')).trim(),website:String(d.get('website')).trim(),category:String(d.get('category')),description:String(d.get('description')).trim(),booking_url:String(d.get('booking_url')||'').trim(),updated_at:new Date().toISOString()};const p=await c.from('provider_profiles').upsert(values);if(p.error)throw p.error;profile=values;draw();renderPreview();msg('Dein Anbieterprofil wurde gespeichert.')}}catch(err){msg(err.message||'Das hat nicht geklappt.',true)}});root.querySelector('[data-provider-logout]').onclick=async()=>{await c.auth.signOut({scope:'local'});user=null;profile=null;draw()};c.auth.onAuthStateChange(event=>{if(event==='PASSWORD_RECOVERY')recovery=true;setTimeout(()=>load().catch(e=>msg(e.message,true)),0)});load().catch(e=>{draw();msg(e.message,true)});
const list=root.querySelector('[data-course-list]'),empty=root.querySelector('[data-course-empty]'),editor=root.querySelector('[data-course-editor]'),courseForm=root.querySelector('[data-provider-form="course"]');
const money=new Intl.NumberFormat('de-CH',{style:'currency',currency:'CHF'}),date=new Intl.DateTimeFormat('de-CH',{dateStyle:'medium',timeStyle:'short'});
async function loadCourses(){const r=await c.from('provider_courses').select('*').eq('provider_id',user.id).order('starts_at',{ascending:true});if(r.error)throw r.error;renderCourses(r.data||[])}
function renderCourses(rows){list.replaceChildren();empty.hidden=rows.length>0;rows.forEach(row=>{const card=document.createElement('article');card.className='provider-course-item';card.innerHTML='<div><span class="provider-course-state '+(row.active?'is-active':'')+'">'+(row.active?'Aktiv':'Pausiert')+'</span><h3></h3><p></p></div><div class="provider-course-actions"><button class="button account-secondary" type="button">Bearbeiten</button><button class="account-text-button" type="button">'+(row.active?'Deaktivieren':'Aktivieren')+'</button><button class="account-text-button provider-delete" type="button">Löschen</button></div>';card.querySelector('h3').textContent=row.title;card.querySelector('p').textContent=date.format(new Date(row.starts_at))+' · '+row.venue+' · '+row.seats+' freie Plätze · '+money.format(row.price);const buttons=card.querySelectorAll('button');buttons[0].onclick=()=>openCourse(row);buttons[1].onclick=async()=>{const q=await c.from('provider_courses').update({active:!row.active,updated_at:new Date().toISOString()}).eq('id',row.id).eq('provider_id',user.id);if(q.error)msg(q.error.message,true);else{msg(row.active?'Kurs wurde deaktiviert.':'Kurs wurde aktiviert.');loadCourses()}};buttons[2].onclick=async()=>{if(!confirm('Diesen Kurs wirklich löschen?'))return;const q=await c.from('provider_courses').delete().eq('id',row.id).eq('provider_id',user.id);if(q.error)msg(q.error.message,true);else{msg('Kurs gelöscht.');loadCourses()}};list.append(card)})}
function openCourse(row=null){courseForm.reset();courseForm.elements.active.checked=true;root.querySelector('[data-course-editor-title]').textContent=row?'Kurs bearbeiten.':'Neuen Kurs erstellen.';if(row){for(const k of ['id','title','category','region','venue','price','seats','booking_url','description'])if(courseForm.elements[k])courseForm.elements[k].value=row[k]??'';courseForm.elements.starts_at.value=new Date(new Date(row.starts_at).getTime()-new Date(row.starts_at).getTimezoneOffset()*60000).toISOString().slice(0,16);courseForm.elements.active.checked=row.active}editor.hidden=false;editor.scrollIntoView({behavior:'smooth',block:'start'})}
root.querySelector('[data-new-course]').onclick=()=>openCourse();root.querySelector('[data-close-course]').onclick=()=>editor.hidden=true;
courseForm.onsubmit=async e=>{e.preventDefault();const d=new FormData(courseForm),id=String(d.get('id')||''),values={provider_id:user.id,title:String(d.get('title')).trim(),category:String(d.get('category')),region:String(d.get('region')),venue:String(d.get('venue')).trim(),starts_at:new Date(String(d.get('starts_at'))).toISOString(),price:Number(d.get('price')),seats:Number(d.get('seats')),booking_url:String(d.get('booking_url')||'').trim(),description:String(d.get('description')).trim(),active:d.get('active')==='on',updated_at:new Date().toISOString()};const q=id?await c.from('provider_courses').update(values).eq('id',id).eq('provider_id',user.id):await c.from('provider_courses').insert(values);if(q.error)msg(q.error.message,true);else{msg(id?'Kurs gespeichert.':'Kurs erstellt.');editor.hidden=true;await loadCourses()}};
function renderPreview(){const box=root.querySelector('[data-provider-preview]');if(!box)return;box.replaceChildren();const card=document.createElement('article');card.className='provider-public-card';const title=document.createElement('h3'),meta=document.createElement('p'),desc=document.createElement('p');title.textContent=profile?.company||'Dein Unternehmen';meta.textContent=[profile?.category,profile?.location].filter(Boolean).join(' · ')||'Kategorie und Standort ergänzen';desc.textContent=profile?.description||'Füge eine Beschreibung hinzu, damit Besucher dein Angebot kennenlernen.';card.append(title,meta,desc);if(profile?.website&&/^https?:\/\//i.test(profile.website)){const a=document.createElement('a');a.className='button account-secondary';a.href=profile.website;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Website besuchen';card.append(a)}box.append(card)}


// Invitation and recovery links establish a session; the owner chooses their own password.
const passwordForm=root.querySelector('[data-provider-password-form]');
passwordForm.onsubmit=async event=>{
 event.preventDefault();if(busy||!passwordForm.reportValidity())return;
 const data=new FormData(passwordForm),password=String(data.get('password'));
 if(password!==String(data.get('confirm'))){msg('Die Passwörter stimmen nicht überein.',true);return;}
 busy=true;const button=passwordForm.querySelector('button');button.disabled=true;msg('');
 try{const result=await c.auth.updateUser({password});if(result.error)throw result.error;passwordForm.reset();recovery=false;draw();msg('Dein Passwort wurde gespeichert. Dein Anbieterzugang ist bereit.');}
 catch(error){msg(error.message||'Passwort konnte nicht gespeichert werden.',true);}
 finally{busy=false;button.disabled=false;}
};
const resetForm=root.querySelector('[data-provider-reset-form]');
resetForm.onsubmit=async event=>{
 event.preventDefault();if(busy||!resetForm.reportValidity())return;
 const email=String(new FormData(resetForm).get('email')).trim();busy=true;const button=resetForm.querySelector('button');button.disabled=true;
 try{const result=await c.auth.resetPasswordForEmail(email,{redirectTo:new URL('/anbieter.html',location.origin).href});if(result.error)throw result.error;msg('Falls ein Konto mit dieser E-Mail-Adresse besteht, erhältst du einen Link zum Festlegen eines neuen Passworts.');}
 catch(error){msg(/sending|smtp|username/i.test(error.message)?'Die E-Mail konnte gerade nicht gesendet werden. Bitte kontaktiere Sponti.':error.message,true);}
 finally{busy=false;button.disabled=false;}
};
const linkError=new URLSearchParams(location.hash.slice(1)).get('error_description');
if(linkError){history.replaceState(null,'',location.pathname+location.search);msg('Dieser Zugangslink ist ungültig oder abgelaufen. Fordere unten einen neuen Passwort-Link an.',true);}
